name: CI

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Teste simples
        run: echo "CI executado com sucesso"
